services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  lgtm:
    image: grafana/otel-lgtm:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - "3000:3000"    # Grafana UI
      - "4317:4317"    # OTLP gRPC receiver
      - "4318:4318"    # OTLP HTTP receiver
      - "55681:55681"  # OpenTelemetry Collector
